# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/apis/01_app.ipynb.

# %% auto 0
__all__ = ['app', 'root']

# %% ../../nbs/apis/01_app.ipynb 2
from fastapi import FastAPI
from .namma_metro import router as metro_router

# %% ../../nbs/apis/01_app.ipynb 3
app = FastAPI(title="Traffic Data Bengaluru API")
app.include_router(metro_router)

@app.get("/")
def root():
    return {"message": "Welcome to Traffic Data Bengaluru API"}
