"""Returns parent ID and registration number of vehicles which match the vehicle number passed in the argument. Ex: `0007` returns `KA53F0007` and `KA57F0007`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/bmtc/apis/03_vehicles.ipynb.

# %% auto 0
__all__ = ['fetch_vehicles', 'process_vehicles', 'get_vehicles']

# %% ../../../nbs/bmtc/apis/03_vehicles.ipynb 7
import string
import json
import time
import datetime
from tqdm import tqdm
import geojson

import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

import requests
import pandas as pd
from fastcore.all import Path
from ...utils import *

# %% ../../../nbs/bmtc/apis/03_vehicles.ipynb 11
def fetch_vehicles(pattern: str = "", sleep_duration: float = 0.1):
    """Fetch vehicles matching the given registration number pattern from BMTC API."""
    time.sleep(sleep_duration)
    url = "https://bmtcmobileapi.karnataka.gov.in/WebAPI/ListVehicles"

    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
        "lan": "en"
    }

    if pattern != '':
        payload = {"vehicleRegNo": pattern}
        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            return response.json()['data']
        except requests.exceptions.RequestException as e:
            print(f"Error: {e}")
            return None
    else:
        vehicles = []
        characters = string.digits + string.ascii_lowercase
        for pattern in tqdm(characters, desc = 'Fetching vehicles'):
            vehicles += fetch_vehicles(pattern)
        return vehicles

# %% ../../../nbs/bmtc/apis/03_vehicles.ipynb 14
def process_vehicles(vehicles):
    """Process and clean vehicle data, returning a DataFrame with `vehicle_id` and `registration_number`."""
    df_vehicles = pd.DataFrame(vehicles)
    df_vehicles = df_vehicles.drop_duplicates(subset=["vehicleregno"], keep="first")

    df_vehicles.rename(columns = {'vehicleid': 'vehicle_id', 'vehicleregno': 'registration_number'}, inplace=True)
    df_vehicles = df_vehicles.sort_values(by='vehicle_id').reset_index(drop=True)
    columns = ['vehicle_id', 'registration_number']
    return df_vehicles[columns]

# %% ../../../nbs/bmtc/apis/03_vehicles.ipynb 17
def get_vehicles(data_directory: Path):
    filepath = get_latest_directory(data_directory / "cleaned" / "vehicles")
    vehicles = pd.read_csv(filepath)
    return vehicles
