# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/namma_metro/01_ridership.ipynb.

# %% auto 0
__all__ = ['logger', 'fetch_ridership', 'task_fetch_ridership']

# %% ../../nbs/namma_metro/01_ridership.ipynb 4
import os
import time
import json
import requests

from fastcore.all import Path

from dotenv import load_dotenv
load_dotenv()

from ..utils import *

# %% ../../nbs/namma_metro/01_ridership.ipynb 5
import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

# %% ../../nbs/namma_metro/01_ridership.ipynb 8
def fetch_ridership(sleep_duration: float = 0.1):
    """Fetch ridership data from the BMRC API."""
    time.sleep(sleep_duration)

    token = os.environ.get("BMRC_TOKEN")

    
    url = "https://english.bmrc.co.in:8282/api/users/getridership"
    headers = {
        "Accept": "application/json",
        "Authorization": f"Bearer {token}"
    }
    response = requests.get(url, headers=headers, verify=False)
    response.raise_for_status()
    return response.json()

# %% ../../nbs/namma_metro/01_ridership.ipynb 11
def task_fetch_ridership(data_directory: Path):
    logger.info("Fetching ridership ...")

    filepath = data_directory / 'raw' / 'ridership.jsonl'
    filepath.parent.mkdir(parents=True, exist_ok=True)

    ridership = fetch_ridership()
    append_to_file(filepath, ridership)

    logger.info(f"Ridership data saved successfully.")
