# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/traffic-data-bengaluru',
                'doc_host': 'https://traffic-kowshik.github.io',
                'git_url': 'https://github.com/traffic-kowshik/traffic-data-bengaluru',
                'lib_path': 'traffic_data_bengaluru'},
  'syms': {'traffic_data_bengaluru.core': {'traffic_data_bengaluru.core.foo': ('core.html#foo', 'traffic_data_bengaluru/core.py')}}}
