"""Utility functions used throughout the project."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['get_repository_directory', 'get_data_directory', 'get_latest_file', 'extract_file', 'extract_files',
           'get_latest_directory', 'read_file']

# %% ../nbs/utils.ipynb 5
import tarfile
import json
import pandas as pd
from fastcore.all import Path

from nbdev.config import get_config
from pathlib import Path
from io import TextIOWrapper

import warnings
warnings.filterwarnings("ignore")

# %% ../nbs/utils.ipynb 7
def get_repository_directory():
    cfg = get_config()
    project_root = Path(cfg.nbs_path).parent
    return project_root

# %% ../nbs/utils.ipynb 10
def get_data_directory():
    data_directory = get_repository_directory() / 'data'
    data_directory.mkdir(parents=True, exist_ok=True)
    return data_directory

# %% ../nbs/utils.ipynb 13
def get_latest_file(directory: Path):
    "Return the latest file, sorting by name for a given directory. Only returns files, not directories."
    files = (
        directory
        .ls()
        .filter(lambda f: not f.name.startswith('.') and f.is_file())
        .sorted(key=lambda f: f.name)
    )
    if len(files) > 0:
        return files[-1]

# %% ../nbs/utils.ipynb 16
def extract_file(filepath: Path):

    if filepath.suffix != ".gz":
        return filepath

    extract_dir = filepath.parent
    extracted_files = []

    with tarfile.open(filepath, "r:gz") as tar:
        for member in tar.getmembers():
            if Path(member.name).name.startswith("._"):
                continue
            tar.extract(member, path=extract_dir)
            extracted_files.append(extract_dir / member.name)

    for du_file in extract_dir.glob("._*"):
        du_file.unlink()

    if len(extracted_files) != 1:
        assert False, f"Expected 1 file, got {len(extracted_files)}"
    return extracted_files[0]

# %% ../nbs/utils.ipynb 19
def extract_files(filepath: Path):

    # When the filepath is not compressed, return files in the directory.
    if filepath.suffix != ".gz":
        return filepath.ls()

    extract_dir = filepath.parent
    extracted_files = []

    with tarfile.open(filepath, "r:gz") as tar:
        for member in tar.getmembers():
            if Path(member.name).name.startswith("._"):
                continue
            tar.extract(member, path=extract_dir)
            extracted_files.append(extract_dir / member.name)

    for du_file in extract_dir.glob("._*"):
        du_file.unlink()
    return extracted_files

# %% ../nbs/utils.ipynb 23
def get_latest_directory(directory: Path):
    "Return the latest subdirectory, sorting by name for a given directory. Only returns directories, not files."
    directories = (
        directory
        .ls()
        .filter(lambda f: not f.name.startswith('.') and f.is_dir())
        .sorted(key=lambda f: f.name)
    )
    
    if len(directories):
        latest = directories[-1]
        return latest

# %% ../nbs/utils.ipynb 26
def read_file(filepath: Path, format: str = 'json'):
    "Read a file in either JSON or CSV format and return its contents."
    with open(filepath) as f:
        if format == 'json':
            return json.load(f)
        elif format == 'csv':
            return pd.read_csv(f)
        else:
            raise ValueError(f"Unsupported format: {format}")
