"""Utility functions used throughout the project."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['get_repository_directory', 'get_data_directory', 'get_latest_directory', 'read_file']

# %% ../nbs/utils.ipynb 5
import json
import pandas as pd
from fastcore.all import Path

from nbdev.config import get_config
from pathlib import Path

# %% ../nbs/utils.ipynb 7
def get_repository_directory():
    cfg = get_config()
    project_root = Path(cfg.nbs_path).parent
    return project_root

# %% ../nbs/utils.ipynb 10
def get_data_directory():
    data_dir = get_repository_directory() / 'data'
    data_dir.mkdir(parents=True, exist_ok=True)
    return data_dir

# %% ../nbs/utils.ipynb 13
def get_latest_directory(directory: Path):
    "Return the latest directory, sorting by name for a given directory."
    latest = (directory 
        .ls() 
        .filter(lambda f: not f.name.startswith('.')) 
        .sorted(key=lambda f: f.name)[-1]
    )
    return latest

# %% ../nbs/utils.ipynb 17
def read_file(filepath: Path, format: str = 'json'):
    "Read a file in either JSON or CSV format and return its contents."
    with open(filepath) as f:
        if format == 'json':
            return json.load(f)
        elif format == 'csv':
            return pd.read_csv(f)
        else:
            raise ValueError(f"Unsupported format: {format}")
