# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/traffic/01_bmtc.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../../nbs/traffic/01_bmtc.ipynb 4
import string
import json
import time
import datetime
from tqdm import tqdm

import requests
import pandas as pd
from fastcore.all import Path
from ..utils import *
from .route_details import *
from nbdev.config import get_config

# %% ../../nbs/traffic/01_bmtc.ipynb 5
import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)
